### ISSUE TITLE
Updating App::cloc Version in CPAN from 1.68 to 1.74

### ISSUE THREAD

**Issue by Happy86** [fibo/App-cloc-pm#3]
Hi, 

I just noticed that the version 1.68 on CPAN still suffers the bug described in [https://github.com/AlDanial/cloc/issues/105](https://github.com/AlDanial/cloc/issues/105). 

Hope it is OK if some random person references [https://github.com/AlDanial/cloc/issues/83](https://github.com/AlDanial/cloc/issues/83) to ask for a new version on CPAN. :-) 

Version 1.74 seems to be the newest stable release. 
[https://github.com/AlDanial/cloc/releases](https://github.com/AlDanial/cloc/releases)

Thank you. 

Best regards, 
Andreas

**Comment by fibo** [comment]
Sorry for the late answer, I just uploaded to CPAN version v1.76, thank you for remember it to me.

**Comment by Happy86** [comment]
Thank you. No problem - it's volunteer work afterall. :-) :+1:
